package com.robin.demo.service;

import java.util.Date;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car0_id
     *
     * @mbggenerated
     */
    private Integer car0Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.series_id
     *
     * @mbggenerated
     */
    private Integer seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.sub_brand_name
     *
     * @mbggenerated
     */
    private String subBrandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.series_name
     *
     * @mbggenerated
     */
    private String seriesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.series_full_name
     *
     * @mbggenerated
     */
    private String seriesFullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.is_inlet
     *
     * @mbggenerated
     */
    private Boolean isInlet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.intake
     *
     * @mbggenerated
     */
    private String intake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.automatic
     *
     * @mbggenerated
     */
    private String automatic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.emission
     *
     * @mbggenerated
     */
    private Float emission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.seat_amount
     *
     * @mbggenerated
     */
    private Integer seatAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.dealer_amount
     *
     * @mbggenerated
     */
    private Integer dealerAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.market_price
     *
     * @mbggenerated
     */
    private Float marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.refer_price
     *
     * @mbggenerated
     */
    private Float referPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.pic_url
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.summary_pic_url
     *
     * @mbggenerated
     */
    private String summaryPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.saled
     *
     * @mbggenerated
     */
    private Integer saled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.buying
     *
     * @mbggenerated
     */
    private Integer buying;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.metioned_days
     *
     * @mbggenerated
     */
    private Integer metionedDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.oem
     *
     * @mbggenerated
     */
    private String oem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.inventory
     *
     * @mbggenerated
     */
    private Integer inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.hot
     *
     * @mbggenerated
     */
    private Float hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.tag
     *
     * @mbggenerated
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.autohome
     *
     * @mbggenerated
     */
    private String autohome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.city_id
     *
     * @return the value of car.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.city_id
     *
     * @param cityId the value for car.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car0_id
     *
     * @return the value of car.car0_id
     *
     * @mbggenerated
     */
    public Integer getCar0Id() {
        return car0Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car0_id
     *
     * @param car0Id the value for car.car0_id
     *
     * @mbggenerated
     */
    public void setCar0Id(Integer car0Id) {
        this.car0Id = car0Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.brand_id
     *
     * @return the value of car.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.brand_id
     *
     * @param brandId the value for car.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.series_id
     *
     * @return the value of car.series_id
     *
     * @mbggenerated
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.series_id
     *
     * @param seriesId the value for car.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.name
     *
     * @return the value of car.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.name
     *
     * @param name the value for car.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.brand_name
     *
     * @return the value of car.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.brand_name
     *
     * @param brandName the value for car.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.sub_brand_name
     *
     * @return the value of car.sub_brand_name
     *
     * @mbggenerated
     */
    public String getSubBrandName() {
        return subBrandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.sub_brand_name
     *
     * @param subBrandName the value for car.sub_brand_name
     *
     * @mbggenerated
     */
    public void setSubBrandName(String subBrandName) {
        this.subBrandName = subBrandName == null ? null : subBrandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.series_name
     *
     * @return the value of car.series_name
     *
     * @mbggenerated
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.series_name
     *
     * @param seriesName the value for car.series_name
     *
     * @mbggenerated
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName == null ? null : seriesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.series_full_name
     *
     * @return the value of car.series_full_name
     *
     * @mbggenerated
     */
    public String getSeriesFullName() {
        return seriesFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.series_full_name
     *
     * @param seriesFullName the value for car.series_full_name
     *
     * @mbggenerated
     */
    public void setSeriesFullName(String seriesFullName) {
        this.seriesFullName = seriesFullName == null ? null : seriesFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.is_inlet
     *
     * @return the value of car.is_inlet
     *
     * @mbggenerated
     */
    public Boolean getIsInlet() {
        return isInlet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.is_inlet
     *
     * @param isInlet the value for car.is_inlet
     *
     * @mbggenerated
     */
    public void setIsInlet(Boolean isInlet) {
        this.isInlet = isInlet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.intake
     *
     * @return the value of car.intake
     *
     * @mbggenerated
     */
    public String getIntake() {
        return intake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.intake
     *
     * @param intake the value for car.intake
     *
     * @mbggenerated
     */
    public void setIntake(String intake) {
        this.intake = intake == null ? null : intake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.year
     *
     * @return the value of car.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.year
     *
     * @param year the value for car.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.automatic
     *
     * @return the value of car.automatic
     *
     * @mbggenerated
     */
    public String getAutomatic() {
        return automatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.automatic
     *
     * @param automatic the value for car.automatic
     *
     * @mbggenerated
     */
    public void setAutomatic(String automatic) {
        this.automatic = automatic == null ? null : automatic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.emission
     *
     * @return the value of car.emission
     *
     * @mbggenerated
     */
    public Float getEmission() {
        return emission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.emission
     *
     * @param emission the value for car.emission
     *
     * @mbggenerated
     */
    public void setEmission(Float emission) {
        this.emission = emission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.seat_amount
     *
     * @return the value of car.seat_amount
     *
     * @mbggenerated
     */
    public Integer getSeatAmount() {
        return seatAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.seat_amount
     *
     * @param seatAmount the value for car.seat_amount
     *
     * @mbggenerated
     */
    public void setSeatAmount(Integer seatAmount) {
        this.seatAmount = seatAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.dealer_amount
     *
     * @return the value of car.dealer_amount
     *
     * @mbggenerated
     */
    public Integer getDealerAmount() {
        return dealerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.dealer_amount
     *
     * @param dealerAmount the value for car.dealer_amount
     *
     * @mbggenerated
     */
    public void setDealerAmount(Integer dealerAmount) {
        this.dealerAmount = dealerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.price
     *
     * @return the value of car.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.price
     *
     * @param price the value for car.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.market_price
     *
     * @return the value of car.market_price
     *
     * @mbggenerated
     */
    public Float getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.market_price
     *
     * @param marketPrice the value for car.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(Float marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.refer_price
     *
     * @return the value of car.refer_price
     *
     * @mbggenerated
     */
    public Float getReferPrice() {
        return referPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.refer_price
     *
     * @param referPrice the value for car.refer_price
     *
     * @mbggenerated
     */
    public void setReferPrice(Float referPrice) {
        this.referPrice = referPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.pic_url
     *
     * @return the value of car.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.pic_url
     *
     * @param picUrl the value for car.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.summary_pic_url
     *
     * @return the value of car.summary_pic_url
     *
     * @mbggenerated
     */
    public String getSummaryPicUrl() {
        return summaryPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.summary_pic_url
     *
     * @param summaryPicUrl the value for car.summary_pic_url
     *
     * @mbggenerated
     */
    public void setSummaryPicUrl(String summaryPicUrl) {
        this.summaryPicUrl = summaryPicUrl == null ? null : summaryPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.saled
     *
     * @return the value of car.saled
     *
     * @mbggenerated
     */
    public Integer getSaled() {
        return saled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.saled
     *
     * @param saled the value for car.saled
     *
     * @mbggenerated
     */
    public void setSaled(Integer saled) {
        this.saled = saled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.buying
     *
     * @return the value of car.buying
     *
     * @mbggenerated
     */
    public Integer getBuying() {
        return buying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.buying
     *
     * @param buying the value for car.buying
     *
     * @mbggenerated
     */
    public void setBuying(Integer buying) {
        this.buying = buying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.metioned_days
     *
     * @return the value of car.metioned_days
     *
     * @mbggenerated
     */
    public Integer getMetionedDays() {
        return metionedDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.metioned_days
     *
     * @param metionedDays the value for car.metioned_days
     *
     * @mbggenerated
     */
    public void setMetionedDays(Integer metionedDays) {
        this.metionedDays = metionedDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.oem
     *
     * @return the value of car.oem
     *
     * @mbggenerated
     */
    public String getOem() {
        return oem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.oem
     *
     * @param oem the value for car.oem
     *
     * @mbggenerated
     */
    public void setOem(String oem) {
        this.oem = oem == null ? null : oem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.inventory
     *
     * @return the value of car.inventory
     *
     * @mbggenerated
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.inventory
     *
     * @param inventory the value for car.inventory
     *
     * @mbggenerated
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.hot
     *
     * @return the value of car.hot
     *
     * @mbggenerated
     */
    public Float getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.hot
     *
     * @param hot the value for car.hot
     *
     * @mbggenerated
     */
    public void setHot(Float hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.tag
     *
     * @return the value of car.tag
     *
     * @mbggenerated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.tag
     *
     * @param tag the value for car.tag
     *
     * @mbggenerated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.autohome
     *
     * @return the value of car.autohome
     *
     * @mbggenerated
     */
    public String getAutohome() {
        return autohome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.autohome
     *
     * @param autohome the value for car.autohome
     *
     * @mbggenerated
     */
    public void setAutohome(String autohome) {
        this.autohome = autohome == null ? null : autohome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.created_at
     *
     * @return the value of car.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.created_at
     *
     * @param createdAt the value for car.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Car{" +
                "id=" + id +
                ", cityId=" + cityId +
                ", car0Id=" + car0Id +
                ", brandId=" + brandId +
                ", seriesId=" + seriesId +
                ", name='" + name + '\'' +
                ", brandName='" + brandName + '\'' +
                ", subBrandName='" + subBrandName + '\'' +
                ", seriesName='" + seriesName + '\'' +
                ", seriesFullName='" + seriesFullName + '\'' +
                ", isInlet=" + isInlet +
                ", intake='" + intake + '\'' +
                ", year='" + year + '\'' +
                ", automatic='" + automatic + '\'' +
                ", emission=" + emission +
                ", seatAmount=" + seatAmount +
                ", dealerAmount=" + dealerAmount +
                ", price=" + price +
                ", marketPrice=" + marketPrice +
                ", referPrice=" + referPrice +
                ", picUrl='" + picUrl + '\'' +
                ", summaryPicUrl='" + summaryPicUrl + '\'' +
                ", saled=" + saled +
                ", buying=" + buying +
                ", metionedDays=" + metionedDays +
                ", oem='" + oem + '\'' +
                ", inventory=" + inventory +
                ", hot=" + hot +
                ", tag=" + tag +
                ", autohome='" + autohome + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.updated_at
     *
     * @return the value of car.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.updated_at
     *
     * @param updatedAt the value for car.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}